# Startseite
index:
    path: /
    controller: App\Controller\IndexController::indexAction

# Registrierung
registration:
    path: /registration
    controller: App\Controller\RegistrationController::indexAction

addUser:
    path: /registration/addUser
    controller: App\Controller\RegistrationController::addUserAction

# Login
login:
    path: /login
    controller: App\Controller\LoginController::indexAction

user:
    path: /login/user
    controller: App\Controller\LoginController::loginAction