-- MySQL Script generated by MySQL Workbench
-- Fri Feb  2 14:46:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tool
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wg_suche` ;

-- -----------------------------------------------------
-- Schema tool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wg_suche` DEFAULT CHARACTER SET utf8 ;
USE `wg_suche` ;

-- -----------------------------------------------------
-- Table `wg_suche`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wg_suche`.`users` ;

CREATE TABLE IF NOT EXISTS `wg_suche`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(2500) NULL,
  `lastname` VARCHAR(2500) NULL,
  `email` VARCHAR(2500) NULL,
  `password` VARCHAR(2500) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wg_suche`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wg_suche`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(2500) NULL,
  `headline` VARCHAR(2500) NULL,
  `street` VARCHAR(2500) NULL,
  `number` VARCHAR(2500) NULL,
  `post_code` VARCHAR(2500) NULL,
  `city` VARCHAR(2500) NULL,
  `public` VARCHAR(2500) NULL,
  `arrival` VARCHAR(2500) NULL,
  `rental_charges` VARCHAR(2500) NULL,
  `room_size` VARCHAR(2500) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
